# Spring properties
spring:
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      uri: mongodb://192.168.99.100/mibarvirtual


# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port